name: Build and Publish package 
on:
  release:
    types: [created]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven - scala-2.12
        run: mvn -B -Pscala-2.12 package --file pom.xml

      - name: Publish package - scala-2.12
        run: mvn -B -Pscala-2.12 deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Clean working directory 
        run: mvn -B clean

      - name: Build with Maven - scala-2.13
        run: mvn -B -Pscala-2.13 package --file pom.xml

      - name: Publish package - scala-2.13
        run: mvn -B -Pscala-2.13 deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
