name: Build and Publish package 
on:
  push:
    branches: [ "tca-154" ]
  release:
    types: [created]
jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish package
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
